#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

load="$(printf '%03d'  $[100-$(vmstat 1 2|tail -1|awk '{print $15}')])"

# full text
echo "$load%"

# short text
echo "$load%"

if [ "$load" -gt "85" ];
then
	echo "#FF0000"
elif [ "$load" -gt "70" ];
then
	echo "#FFAE00"
elif [ "$load" -gt "60" ];
then
	echo "#FFF600"
else
	echo "#00FF00"
fi
